### PR TITLE
Added ability to pass control.ergm() to btergm

### PR DESCRIPTION
**Pull request by reuning**
Not sure if this is wanted but I needed to change the max dyad size so added some lines to allow you to pass control.ergm on. It probably won't be very useful outside of changing the max dyad but I wasn't sure so I made it more generic.

### CODE REVIEW

**Comment by leifeld** [comment]
Hi there! Thanks for your pull request and continued work on this. Let me know when you are done with your changes, and I'll review the changes. I think it makes sense to offer fastglm support now that it is available.

**Comment by reuning** [comment]
Sure. I hadn't realized that the pull request would keep updating (I'm still relatively new to actually using github). I'll let you know when it gets to a stable spot.

**Comment by leifeld** [comment]
Hi there. I am aiming to release a new version next weekend. It would be ideal if you could wrap up your changes by then in order to avoid any conflicts that need to be integrated into your PR. Thanks.

**Comment by reuning** [comment]
I'll clean things up this week. 

I have it currently set so that fastglm is not the default (switched on with `usefastglm=T`) Do you have a preference for this?

**Comment by leifeld** [comment]
Great, thanks! I'd prefer to keep it that way for now in order to match the description in the article in the Journal of Statistical Software that came out last year.

**Comment by reuning** [comment]
There that should be everything.

**Comment by leifeld** [comment]
Excellent, thanks! I have made some minor changes to comply with CRAN guidelines and improve formatting. Will merge now.

**Pull request merged**
